// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rosfwojntjegzoirnhcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvc2Z3b2pudGplZ3pvaXJuaGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzgyMDEsImV4cCI6MjA2MjI1NDIwMX0.0BxOAbGmLC-Oef8cWghDyge24Q4LUIMq-pIA4trrcIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);