// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeuzzlqvdpewgzukmtow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldXp6bHF2ZHBld2d6dWttdG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDM4NDUsImV4cCI6MjA2MzE3OTg0NX0.AZs4CHwiF-CDPUQ0en0OwlpG8eMf1o4vYgu-i-qiyXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);